language: node_js
node_js:
 - "6"
 - "7"
 - "8"
 - "9"
 - "10"
install:
- yarn install
script:
- npm run lint
- npm run compile
- npm run test

jobs:
  include:
    - stage: after_success
      script:
      - yarn install
      - npm run compile
      - npm run coveralls
      node_js: 9
