language: node_js
node_js:
 - "4"
 - "6"
 - "7"
 - "8"
 - "9"
install:
- npm install
script:
- npm run test

jobs:
  include:
    - stage: before_install
      script: npm run lint
      node_js: 8
    - stage: before_script
      script: npm run compile
      node_js: 8
    - stage: after_success
      script: npm run coveralls
      node_js: 8
