language: node_js

node_js:
- "4"
- "6"
- "7"
- "8"
- "9"
- "10"

jobs:
  include:
    - stage: check code
      script: npm run lint
    - stage: test
      script: npm run lint
      script: npm run compile
      script: npm run coveralls
    - stage: before_script
      script: npm install typescript@2.0
      node_js: 4
    - stage: before_script
      script: npm install typescript@2.4
      node_js: 6

    - stage: after_success
      script: npm run coveralls
      node_js: 9

matrix:
  allow_failures:
  - node_js: 10