language: node_js
node_js:
 - "6"
 - "7"
 - "8"
 - "9"

jobs:
  include:
    - stage: install_dependencies
      script: npm install
    - stage: check_code
      script: npm run lint
    - stage: compile
      script: npm run compile
    - stage: test
      script: npm run test
    - stage: after_success
      script: npm run coveralls
      node_js: 8
