language: node_js

jobs:
  include:
    - stage: check code
      script: npm run lint
      node_js: 9

    - stage: compile
      script: npm install typescript@2.0
      script: npm run compile
      node_js: 4
    - stage: compile
      script: npm install typescript@2.4
      script: npm run compile
      node_js: 6
    - stage: compile
      script: npm run compile
      node_js: 7
    - stage: compile
      script: npm run compile
      node_js: 8
    - stage: compile
      script: npm run compile
      node_js: 9
    - stage: compile
      script: npm run compile
      node_js: 10

    - stage: test
      script: npm run test
      node_js: 4
    - stage: test
      script: npm run test
      node_js: 6
    - stage: test
      script: npm run test
      node_js: 7
    - stage: test
      script: npm run test
      node_js: 8
    - stage: test
      script: npm run test
      node_js: 9
    - stage: test
      script: npm run test
      node_js: 10

    - stage: after_success
      script: npm run coveralls
      node_js: 9

matrix:
  allow_failures:
  - node_js: 10