language: node_js

jobs:
  include:
    - stage: npm install
      script: npm run compile
      node_js: 8
    - stage: compile
      script: npm run compile
      node_js: 8
    - stage: test
      script: npm run lint
      script: npm run test
      node_js: 7
    - stage: test
      script: npm run lint
      script: npm run test
      node_js: 8
    - stage: test
      script: npm run lint
      script: npm run test
      node_js: 9
    - stage: after_success
      script: npm run coveralls
      node_js: 8
